export const constants = {
  PASSENGER: 'passenger',
  DRIVER: 'driver',
  PASSENGER_FIELD: 'default_address',
  EMPTY: '',
  PICTURE_KEY: 'picture',
  AGE_KEY: 'age',
  ID_KEY: 'id',
  USER_TYPE_KEY: 'user_type',
  TOKEN_KEY: 'token',
  USER_NOT_FOUND_ERROR: 'Firebase: Error (auth/user-not-found).',
  DEFAULT_URL_USER_PICTURE: 'https://cdn.icon-icons.com/icons2/3065/PNG/512/profile_user_account_icon_190938.png',
  DRIVER_NOT_EXIST_ERROR: 'The driver does not exists',
  PASSENGER_NOT_EXIST_ERROR: 'The passenger does not exists',
};
